package com.codeguardian.infrastructure.gemini.dto;

import com.codeguardian.domain.model.ReviewComment;
import com.codeguardian.domain.model.ReviewReport;

import java.util.List;
import java.util.stream.Collectors;

/**
 * DTO to deserialize the structured JSON review result generated by Gemini.
 */
public class GeminiReviewReportDto {
    private String summary;
    private Integer overallScore;
    private List<CommentDto> comments;

    public GeminiReviewReportDto() {}

    public GeminiReviewReportDto(String summary, Integer overallScore, List<CommentDto> comments) {
        this.summary = summary;
        this.overallScore = overallScore;
        this.comments = comments;
    }

    public String getSummary() { return summary; }
    public void setSummary(String summary) { this.summary = summary; }

    public Integer getOverallScore() { return overallScore; }
    public void setOverallScore(Integer overallScore) { this.overallScore = overallScore; }

    public List<CommentDto> getComments() { return comments; }
    public void setComments(List<CommentDto> comments) { this.comments = comments; }

    /**
     * Translates this deserialized DTO structure into domain model objects.
     */
    public ReviewReport toDomain() {
        List<ReviewComment> domainComments = comments == null ? List.of() :
                comments.stream()
                        .map(CommentDto::toDomain)
                        .collect(Collectors.toList());
        return new ReviewReport(summary, overallScore, domainComments);
    }

    public static class CommentDto {
        private String filePath;
        private Integer lineNumber;
        private String category;
        private String commentText;

        public CommentDto() {}

        public CommentDto(String filePath, Integer lineNumber, String category, String commentText) {
            this.filePath = filePath;
            this.lineNumber = lineNumber;
            this.category = category;
            this.commentText = commentText;
        }

        public String getFilePath() { return filePath; }
        public void setFilePath(String filePath) { this.filePath = filePath; }

        public Integer getLineNumber() { return lineNumber; }
        public void setLineNumber(Integer lineNumber) { this.lineNumber = lineNumber; }

        public String getCategory() { return category; }
        public void setCategory(String category) { this.category = category; }

        public String getCommentText() { return commentText; }
        public void setCommentText(String commentText) { this.commentText = commentText; }

        public ReviewComment toDomain() {
            return new ReviewComment(filePath, lineNumber, category, commentText);
        }
    }
}
