package com.codeguardian.usecases.service;

import com.codeguardian.domain.model.CodeSnippet;
import com.codeguardian.domain.model.PullRequest;
import com.codeguardian.domain.model.Review;
import com.codeguardian.domain.model.ReviewComment;
import com.codeguardian.usecases.port.out.EmbeddingClientPort;
import com.codeguardian.usecases.port.out.GeminiClientPort;
import com.codeguardian.usecases.port.out.PullRequestRepositoryPort;
import com.codeguardian.usecases.port.out.ReviewRepositoryPort;
import com.codeguardian.usecases.port.out.VectorStorePort;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;

/**
 * Service orchestrating interactive chat conversations about specific PR reviews.
 */
@Service
public class ReviewChatService {

    private static final Logger log = LoggerFactory.getLogger(ReviewChatService.class);

    private final ReviewRepositoryPort reviewRepository;
    private final PullRequestRepositoryPort pullRequestRepository;
    private final GeminiClientPort geminiClient;
    private final EmbeddingClientPort embeddingClient;
    private final VectorStorePort vectorStore;

    public ReviewChatService(ReviewRepositoryPort reviewRepository,
                             PullRequestRepositoryPort pullRequestRepository,
                             GeminiClientPort geminiClient,
                             EmbeddingClientPort embeddingClient,
                             VectorStorePort vectorStore) {
        this.reviewRepository = reviewRepository;
        this.pullRequestRepository = pullRequestRepository;
        this.geminiClient = geminiClient;
        this.embeddingClient = embeddingClient;
        this.vectorStore = vectorStore;
    }

    /**
     * Contextual chat with Gemini about a specific code review.
     *
     * @param reviewId the review's internal database UUID
     * @param userMessage the developer's chat message
     * @return the response generated by the Gemini model
     */
    public String chatAboutReview(UUID reviewId, String userMessage) {
        log.info("Processing interactive review chat for reviewId: {}", reviewId);

        Review review = reviewRepository.findById(reviewId)
                .orElseThrow(() -> new IllegalArgumentException("Review not found for ID: " + reviewId));

        // Gather review context
        StringBuilder reviewContext = new StringBuilder();
        reviewContext.append("Review ID: ").append(review.getId()).append("\n")
                .append("Overall Score: ").append(review.getOverallScore()).append("/100\n")
                .append("Executive Summary:\n").append(review.getSummary()).append("\n\n")
                .append("Specific Review Recommendations:\n");

        if (review.getComments() != null && !review.getComments().isEmpty()) {
            for (ReviewComment comment : review.getComments()) {
                reviewContext.append("- [File: ").append(comment.getFilePath())
                        .append(", Line: ").append(comment.getLineNumber())
                        .append(", Category: ").append(comment.getCategory()).append("] ")
                        .append(comment.getCommentText()).append("\n");
            }
        } else {
            reviewContext.append("No specific comments or warnings were generated.\n");
        }

        // Gather relevant codebase context via RAG vector search
        String codebaseContext = "";
        try {
            float[] queryEmbedding = embeddingClient.generateEmbedding(userMessage);
            List<CodeSnippet> snippets = vectorStore.findSimilar(queryEmbedding, 3);
            if (!snippets.isEmpty()) {
                StringBuilder contextBuilder = new StringBuilder();
                for (CodeSnippet snippet : snippets) {
                    contextBuilder.append("File: ").append(snippet.getFilePath())
                            .append(" (Lines ").append(snippet.getStartLine()).append("-").append(snippet.getEndLine()).append(")\n")
                            .append("Code Snippet:\n")
                            .append(snippet.getContent()).append("\n\n");
                }
                codebaseContext = contextBuilder.toString().trim();
            }
        } catch (Exception e) {
            log.warn("Failed to retrieve codebase RAG context for chat interaction: {}", e.getMessage());
        }

        // Build the system prompt
        String systemInstruction = "You are an AI code reviewer assistant. You are helping a developer understand and address the recommendations generated during a code review.\n" +
                "Here is the context of the code review:\n" +
                reviewContext.toString() + "\n" +
                (codebaseContext.isEmpty() ? "" : "Here is some relevant codebase context retrieved from the repository database:\n" + codebaseContext + "\n") +
                "Answer the developer's questions about these recommendations, suggesting specific code fixes or explaining the reasoning behind the review. Be polite, precise, and highly technical.";

        // Invoke Gemini to generate the chat response
        return geminiClient.generateContent(systemInstruction, userMessage);
    }
}
